name: Quality

on:
    pull_request:
        branches:
            - master

jobs:
    build_components:
        name: Install Dependencies
        runs-on: ubuntu-latest
        steps:
            - name: Check out source code
              uses: actions/checkout@v3
            - name: Set up node
              uses: actions/setup-node@v1
              with:
                  node-version: '18.18'
            - name: use cache
              uses: actions/cache@v3
              with:
                  path: '**/node_modules'
                  key: ${{ runner.os }}-modules-${{ hashFiles('**/deps.lock') }}
            - name: Install Components dependencies
              run: |
                  cd packages/ui
                  npm install
            - name: Install Components dependencies
              run: |
                  cd packages/ui
                  npm install
                  npm run build
                  cd ../../storybook
                  npm install

    tests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Install modules
              run: |
                  cd packages/ui
                  npm i
            - name: Run tests
              id: tests
              run: |
                  cd packages/ui
                  echo " " >> results.log
                  echo "## Project Coverage and Test" >> results.log
                  echo "" >> results.log
                  echo "`npm run test:github  2>&1 | sed 's/=//g' | tail -n 11`" >> results.log
                  echo " " >> results.log
            - uses: marocchino/sticky-pull-request-comment@v2
              with:
                  header: Project Coverage and Test
                  path: packages/ui/results.log
