---
name: Shai-Hulud detection
on:
  push:
  workflow_dispatch:

jobs:
  shai-hulud-scanner:  # https://github.com/sngular/shai-hulud-integrity-scanner/tree/main
    runs-on: ubuntu-latest
    name: Detect known Shai-Hulud signatures
    steps:
      - uses: actions/checkout@v2
      - name: Shai-Hulud scan-project.sh
        if: ${{ hashFiles('**/package-lock.json') != '' }}
        run: |
          rm -rf $GITHUB_WORKSPACE/.github  # disable workflow scan
          curl -s https://raw.githubusercontent.com/sngular/shai-hulud-integrity-scanner/refs/heads/main/scan-project.sh | bash /dev/stdin $GITHUB_WORKSPACE
        #  continue-on-error: true
